spring.application.name=notification-service
# =========================
# PUERTO
# =========================
server.port=8082

# =========================
# POSTGRESQL (COMMAND SIDE)
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/notifications
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# MONGODB (QUERY SIDE)
# =========================
spring.data.mongodb.uri=mongodb://localhost:27017/notifications

# =========================
# PROVEEDORES SMS
# =========================
aldeamo.url=http://localhost:8083
twilio.url=http://localhost:8084

# =========================
# RESILIENCE4J
# =========================
resilience4j.circuitbreaker.instances.aldeamoCB.sliding-window-size=5
resilience4j.circuitbreaker.instances.aldeamoCB.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.aldeamoCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.aldeamoCB.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.aldeamoCB.permitted-number-of-calls-in-half-open-state=1

# =========================
# FEIGN
# =========================
feign.client.config.default.loggerLevel=FULL

# =========================
# LOGS
# =========================
logging.level.org.springframework.cloud.openfeign=DEBUG
logging.level.io.github.resilience4j=DEBUG
logging.level.com.example.notification_service=INFO