spring.application.name=pago-service

# =========================
# PUERTO
# =========================
server.port=8081

# =========================
# NOTIFICATION SERVICE
# A TRAVÉS DE KONG
# =========================
notification.url=http://localhost:8000/api

# =========================
# FEIGN
# =========================
feign.client.config.default.loggerLevel=FULL

# =========================
# LOGS
# =========================
logging.level.org.springframework.cloud.openfeign=DEBUG
logging.level.com.example.pago_service=INFO